package:
  name: oce
  version: 0.18.2

source:
  fn: OCE-0.18.2.tar.gz
  url: https://github.com/tpaviot/oce/archive/OCE-0.18.2.tar.gz
  patches:
    - fix_cmakelist_osx_link.patch

build:
  detect_binary_files_with_prefix: True
  number: 2
  features:
    - vc9               [win and py27]
    - vc14              [win and py35]

requirements:
  build:
    - ninja ==1.7.2
    - gl2ps ==1.3.8
    - freeimageplus ==3.17.0
    - tbb ==2017_20170226
    - python
    - freetype ==2.7
    - cmake ==3.8.0

  run:
    - gl2ps ==1.3.8
    - freeimageplus ==3.17.0
    - tbb ==2017_20170226
    - freetype ==2.7

about:
  home: https://github.com/tpaviot/oce
  license: LGPL
  summary: OpenCASCADE community edition
