# change the version number to "0.17.1" or "0.18" in case of a release build
package:
  name: pythonocc-core
  version: 0.19

source:
  path: ../..


build:
  script_env:
    - CC
    - CXX

  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - python
    - opencascade ==7.4.0
    - cmake
    - ninja ==1.8.2
    - swig ==4.0.1

  run:
    - opencascade ==7.4.0
    - python
    - six

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
    
about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
