# change the version number to "0.17.1" or "0.18" in case of a release build
package:
  name: pythonocc-core
  version: 0.18.2

source:
  path: ../..


build:
  script_env:
    - CC
    - CXX

  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - python
    - oce ==0.18.3
    - tbb
    - tbb-devel
    - cmake
    - ninja ==1.8.2
    - swig ==3.0.12
    - freetype >=2.9
    - smesh ==6.7.6

  run:
    - oce ==0.18.3
    - python
    - tbb
    - freetype
    - smesh ==6.7.6
    - six

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI

    

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
