language: python
python:
  - "2.7"
  - "3.3"
before_install:
   - sudo apt-get install swig
   - sudo add-apt-repository "deb http://ppa.launchpad.net/freecad-maintainers/oce-release/ubuntu precise main" -y
   - sudo apt-get update -q
   - sudo apt-get install liboce-ocaf-dev oce-draw
   - sudo apt-get install python-wxgtk2.8 libwxgtk-2.8-dev
   - sudo apt-get install python-qt4 python-pyside
before_script:
  - mkdir cmake-build
  - cd cmake-build
script: ../.travis.build.sh
after_script:
  - cd ../test
  - python run_tests.py
# test display, different depths
  - xvfb-run -s "-screen 0 1024x768x16" python core_display_unittest.py
  - xvfb-run -s "-screen 0 1024x768x32" python core_display_unittest.py
branches:
  only:
    - master
    - /^review/
