language: cpp
compiler:
  - gcc
  - clang
before_install:
# following ppa contains oce-0.16.0
   - sudo add-apt-repository "deb http://ppa.launchpad.net/freecad-maintainers/oce-release/ubuntu precise main" -y
   - sudo apt-get update -q
   - sudo apt-get install liboce-ocaf-dev oce-draw
   - sudo apt-get install python-wxgtk2.8
   - sudo python -c "import wx"
   - sudo apt-get install python-qt4 python-qt4-gl
   - sudo python -c "from PyQt4 import QtGui, QtCore, QtOpenGL"
   - sudo apt-get install python-pyside
   - sudo python -c "from PySide import QtGui, QtCore, QtOpenGL"
# and this one python3.4 for ubuntu precise
   - sudo add-apt-repository "deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu precise main" -y
   - sudo apt-get update
   - sudo apt-get install python3.4
   - sudo apt-get install python3.4-dev
before_script:
  - wget http://prdownloads.sourceforge.net/swig/swig-2.0.10.tar.gz
# untar swig files generates thousands of lines. Redirect stdout stream
# to a file
  - tar -xvf swig-2.0.10.tar.gz > swig-2.0.10-filelist.txt
  - cd swig-2.0.10
  - ./configure
  - make -j6 && sudo make install
  - cd ..
  - swig -version
script: ./.travis.build.sh
after_script:
branches:
  only:
    - master
    - /^review/
