sudo: false

language: cpp

# the secure below is the binstar token
# to genrate this secure
# first create an anconda cloud token
# $ anaconda auth -n the_token_name -o oce -c --scopes api
# the token is return as something like "oc-6654-12334_111225"
# then encrypt the token
# You have to be in the directory where you installed the local copy of the repository
# $ cd [your_dev_dir]/oce-conda
# $ travis encrypt BINSTAR_TOKEN="oc-6654-12334_11122"
# !!be careful about the typo BINSTAR_TOKEN with the proper case. Otherwise
# !!the $BINSTAR_TOKEN env var value will be null and the line
# !!anaconda -t $BINSTAR_TOKEN upload *.bz2 will not be run properly
# after that, copy/paste the secure on the following line
env:
  global:
    - secure: "XObUZlAdB3tRpDtd0z0LaxbOnkpiulNloSevDl5g8+Z3bsBk6jX0GTkVKSryxwe2H7v+YE8crShPykBvi/MlbXOy5S2nO/PjDxJFBQDsGFygrpOnjJ2bZ0IWSLeHADwVoiZZC2yHmkcaq+c5h/fFNyepfai42jhNLFR69adXOSk="

matrix:
  include:
    - env: ARCH="x86_64"
      os: linux
      dist: trusty
      addons: &gcc5
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
    - env: ARCH="x86_64" MACOSX_DEPLOYMENT_TARGET="10.9"
      os: osx
      osx_image: xcode8.3

# Use miniconda to install binary versions of numpy etc. from continuum
# analytic's repository. Follows an approach described by Dan Blanchard:
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export CXX=g++-7;
      export CC=gcc-7;
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  - chmod +x miniconda.sh
  # When we are installing the 32 Bit conda on a 64 Bit system, the miniconda
  # installer will ask for a "yes" despite the -b flag, so we pipe in a yes
  - yes | ./miniconda.sh -b -p $HOME/miniconda
  #- bash miniconda.sh -b -p -f $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # install everything required to build the receipe
  - conda install conda-build anaconda-client
  # Useful for debugging any issues with conda
  - conda info -a
  # Add dlr-sc channel for third part libraries
  # necessary because of gl2ps
  - conda config --add channels https://conda.anaconda.org/conda-forge
  - conda config --add channels https://conda.anaconda.org/dlr-sc

script:
  #- conda build oce-0.17.2
  #- conda build oce-0.17.3
  #- conda build oce-0.18
  #- conda build oce-0.18.1
  - conda build oce-0.18.2

after_success:
  - python move-conda-package.py
  - anaconda -t $BINSTAR_TOKEN upload *.bz2 --force;

branches:
  only:
    - master
    - build-oce
    - /^review/
